# permissions for end users to view metricsreadinesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsreadiness-viewer-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - metricsreadinesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - metricsreadinesses/status
  verbs:
  - get
