# permissions for end users to edit metricsreadinesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsreadiness-editor-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - metricsreadinesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - metricsreadinesses/status
  verbs:
  - get
